use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006000
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
David
Golden
dagolden
Ricardo
Signes
rjbs
Leon
Brocard
acme
Florian
Ragwitz
rafl
Graham
Knop
haarg
SIGNES
lib
Metabase
Test
Archive
Null
Index
FlatFile
Librarian
Factory
Gateway
Filesystem
Query
Fact
